# Generated by Django 3.2.12 on 2024-02-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_issue_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='link_to_issue',
        ),
    ]
